services:
  test-runner:
    build: .
    container_name: fedemo-ci-container
    environment:
      - CI=true
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report # add this to capture reports locally
    user: "1000:1000" # pwuser's uid:gid in the Playwright base image
